language: java
jdk:
  - openjdk15

before_script:
  - mvn versions:set -DnewVersion=$TRAVIS_TAG
deploy:
  provider: releases
  file: target/Hospital-Project-${TRAVIS_TAG}.jar
  edge: true
  on:
    tags: true
